# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5deaeb286cda38727d9248dd86f782fe8c6224747a069a4c947728c9f85c11845970b7d0ac434ea6f3d03d862cb39dd80318f12ef0577ac467add8b8e79432a

test:
  secret_key_base: fd4ae741d304139258927536ab3eac6577ade4cabf96100566bb9515aed417eee7c3e24c28c12c72bfb71d8de4cb2c3a19c34d0f7aa40bd065ac9b65e398f4c5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
